BlissBase/BlissBase/Controllers/CompositeSymbolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlissBase.BLL;
using BlissBase.Model;

namespace BlissBase.Controllers
{
    /// <summary>
    /// CompositeSymbolController is used to keep
    /// track of CompositeSymbols. The methods here edit and delete the 
    /// CompositeSymbols, and also return appropriate views.
    /// </summary>
    public class CompositeSymbolController : Controller
    {
        /// <summary>
        /// Generates a list of all the CompositeSymbols and 
        /// saves it in ViewData, and then returns the Index-view.
        /// It also sends an error message to the view if it exists.
        /// </summary>
        /// <param></param>
        /// <returns>Index-view</returns>
        public ActionResult Index()
        {
            CompositeSymbolBLL comp = new CompositeSymbolBLL();
            ViewData["comp"] = comp.GetAll();
            if (TempData["msg"] != null)
            {
                ViewBag.Message = TempData["msg"].ToString();
            }
            return View();
        }

        /// <summary>
        /// Gets the id of the CompositeSymbol you want to edit, 
        /// the symbols it is made of, and a list of all Symbols,
        /// saves them in ViewData and then returns the Edit-view.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Edit-view</returns>
        public ActionResult Edit(int id)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            CompositeSymbolBLL comp = new CompositeSymbolBLL();
            CompositeSymbol find = comp.GetExaxtComositeSymbolByID(id);

            CompositeOfBLL compOf = new CompositeOfBLL();

            SymbolBLL symb = new SymbolBLL();

            List<Symbol> symbols = compOf.GetComponentsOf(find);

            SymbolTypeBLL types = new SymbolTypeBLL();

            ViewData["comp"] = find;
            ViewData["symbList"] = symbols;
            ViewData["otherSymbols"] = symb.GetAllSymbols();
            ViewData["Types"] = types.GetAllNonStandard();
            return View();
        }

        /// <summary>
        /// This method takes an Int32-array with id's of Symbols, and a compId
        /// representing the recently changed CompositeSymbol.
        /// Redirects you to the Index-method in CompositeSymbolController,
        /// together with a message of error or success.
        /// </summary>
        /// <param name="isPartOf"></param>
        /// <param name="compId"></param>
        /// <returns>Index-view</returns>
        [HttpPost]
        public ActionResult Edit(Int32[] isPartOf, int compId)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            CompositeSymbolBLL comp = new CompositeSymbolBLL();
            SymbolBLL symbols = new SymbolBLL();

            CompositeSymbol editedComp = comp.GetExaxtComositeSymbolByID(compId);
            List<Symbol> partOf = new List<Symbol>();

            foreach(Int32 part in isPartOf)
            {
                var temp = symbols.GetExactByID(part);
                if(temp != null)
                {
                    partOf.Add(temp);
                }
            }

            CompositeOfBLL compOf = new CompositeOfBLL();
            var ok = compOf.DeleteByCompositeSymbol(editedComp);
            if(ok)
            {
                ok = compOf.SetCompositeOfSymbol(editedComp, partOf);
                if(ok)
                {
                    TempData["msg"] = "Composite Symbol '" + editedComp.compName + "' was successfully edited.";
                }
                else
                {
                    TempData["msg"] = "Error when editing.";
                }
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Takes an id and deletes the corresponding CompositeSymbol.
        /// Returns you to the Index-method of the CompositeSymbolController
        /// together with a message of error or success.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Index-view</returns>
        public ActionResult Delete(int id)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            CompositeSymbolBLL comp = new CompositeSymbolBLL();
            CompositeSymbol toDelete = comp.GetExaxtComositeSymbolByID(id);

            var name = toDelete.compName;

            if (toDelete != null)
            {
                var ok = comp.DeleteCompositeSymbol(toDelete);
                if (ok)
                {
                    TempData["msg"] = "Composite Symbol '" + name + "' was successfully deleted.";
                }
                else
                {
                    TempData["msg"] = "Could not delete symbol '" + name + "'.";
                }
            }
            else
            {
                TempData["msg"] = "Composite Symbol with id: '" + id + "' was not found.";
            }

            return RedirectToAction("Index");
        }
    }
}

BlissBase/BlissBase/Controllers/RawListController.cs
using System;
using System.IO;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlissBase.Model;
using BlissBase.BLL;

namespace BlissBase.Controllers
{
    /// <summary>
    /// RawListController is used to create RawListImports, convert them to either 
    /// CompositeSymbols or Symbols, delete single RawListImports or all. 
    /// </summary>
    public class RawListController : Controller
    {
        /// <summary>
        /// Returns the Index-view together with the list of
        /// all the RawImportSymbols in the DB. Sends a message aswell, if it exists
        /// </summary>
        /// <returns>~/RawList/Index.cshtml</returns>
        public ActionResult Index()
        {
            RawSymbolImportBLL raw = new RawSymbolImportBLL();
            ViewData["raw"] = raw.GetAll();
            if(TempData["msg"] != null)
            {
                ViewBag.Message = TempData["msg"].ToString();
            }

            return View();
        }

        /// <summary>
        /// Returns the byte-array paramater raw
        /// as a jpeg image file.
        /// </summary>
        /// <param name="raw"></param>
        /// <returns>jpeg image file</returns>
        public ActionResult Image(byte[] raw)
        {
            if (raw != null)
                return File(raw, "image/jpeg");
            else
            {
                Debug.WriteLine("Raw Symbol byte[] was null");
                return null;
            }
        }

        /// <summary>
        /// Takes an int id as parameter and finds the corresponding
        /// RawSymbolImport. Saves it in ViewData["raw"] and returns
        /// the AddAsBaseSymbol-view.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>~/RawList/AddAsBaseSymbol.cshtml</returns>
        public ActionResult AddAsBaseSymbol(int id)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            RawSymbolImportBLL rawImport = new RawSymbolImportBLL();
            RawSymbolImport toConvert = rawImport.GetExact(id);

            ViewData["raw"] = toConvert;

            return View();
        }

        /// <summary>
        /// Takes an int rawId and converts the corresponding RawSymbolImport to 
        /// a Symbol with the same type as parameter symbolType.
        /// Redirects to Index-view of SymbolController, together with a message.
        /// </summary>
        /// <param name="rawId"></param>
        /// <param name="symbolType"></param>
        /// <returns>~/Symbol/Index.cshtml</returns>
        [HttpPost]
        public ActionResult AddAsBaseSymbol(int rawId, int symbolType)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            RawSymbolImportBLL rawImport = new RawSymbolImportBLL();
            RawSymbolImport toConvert = rawImport.GetExact(rawId);

            SymbolBLL symbols = new SymbolBLL();
            var returnedId = symbols.Insert(toConvert.rawName, toConvert.rawJpeg);
            if (returnedId != -1)
            {
                TempData["msg"] = "Success";

                RawSymbolImportBLL raws = new RawSymbolImportBLL();
                var ok = raws.DeleteExact(rawId);
                if (!ok)
                {
                    TempData["msg"] += ", but could not delete symbol from raw list.";
                }

                if(symbolType != 0)
                {
                    SymbolTypeBLL symbolTypes = new SymbolTypeBLL();
                    TypeCodes type;
                    
                    if (symbolType == 1)
                    {
                        type = TypeCodes.INDICATOR;
                    }
                    else if (symbolType == 2)
                    {
                        type = TypeCodes.NUMERICAL;
                    }
                    else
                    {
                        type = TypeCodes.LATIN;
                    }

                    symbolTypes.SetLanguageForSymID(returnedId, type);
                }
            }
            else
            {
                TempData["msg"] = "Could not add symbol as base.";
            }

            return RedirectToAction("Index", "Symbol");
        }

        /// <summary>
        /// Takes int id as parameter and finds the corresponding RawSymbolImport.
        /// Saves the RawSymbolImport and a list of all Symbols in Viewdata["raw"] and
        /// Viewdata["symbList"] respectively, and returns the ConvertToComposite-view.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>~/RawList/ConvertToComposite.cshtml</returns>
        public ActionResult ConvertToComposite(int id)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            RawSymbolImportBLL raw = new RawSymbolImportBLL();
            RawSymbolImport find = raw.GetExact(id);

            SymbolBLL symb = new SymbolBLL();

            SymbolTypeBLL types = new SymbolTypeBLL();

            ViewData["raw"] = find;
            ViewData["symbList"] = symb.GetAllSymbols();
            ViewData["types"] = types.GetAllNonStandard();
            return View();
        }

        /// <summary>
        /// Converts the RawSymbolImport with id = rawId to a CompositeSymbol 
        /// made of Symbols with id's stored in the isPartOf-array.
        /// Redirects to the Index-method in the CompositeSymbolController,
        /// together with a message.
        /// </summary>
        /// <param name="isPartOf"></param>
        /// <param name="rawId"></param>
        /// <returns>~/CompositeSymbol/Index.cshtml</returns>
        [HttpPost]
        public ActionResult ConvertToComposite(Int32[] isPartOf, int rawId)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            RawSymbolImportBLL raw = new RawSymbolImportBLL();
            SymbolBLL symbols = new SymbolBLL();
            CompositeSymbolBLL comp = new CompositeSymbolBLL();

            RawSymbolImport rawBecomingComp = raw.GetExact(rawId);
            List<Symbol> partOf = new List<Symbol>();

            foreach (Int32 part in isPartOf)
            {
                var temp = symbols.GetExactByID(part);
                if (temp != null)
                {
                    partOf.Add(temp);
                }
            }

            CompositeSymbol compOfRaw = new CompositeSymbol()
            {
                compId = rawBecomingComp.rawId,
                compName = rawBecomingComp.rawName,
                compJpeg = rawBecomingComp.rawJpeg
            };

            var ok = comp.Insert(compOfRaw, partOf);
            if (ok != -1)
            {
                TempData["msg"] = "Raw symbol '" + rawBecomingComp.rawName + "' is now a composite symbol";
                var successfullyDeleted = raw.DeleteExact(rawId);
                if(!successfullyDeleted)
                {
                    TempData["msg"] += ", but was not deleted from raw list.";
                }
            }
            return RedirectToAction("Index", "CompositeSymbol");
        }

        /// <summary>
        /// Deletes the RawSymbolImport with id as parameter id.
        /// Redirects to the Index-method in RawListController together with
        /// a message of error or success.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>~/RawList/Index.cshtml</returns>
        public ActionResult Delete(int id)
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            RawSymbolImportBLL raw = new RawSymbolImportBLL();
            RawSymbolImport toDelete = raw.GetExact(id);
            
            var name = toDelete.rawName;

            if(toDelete != null)
            {
                var ok = raw.DeleteExact(id);
                if (ok)
                {
                    TempData["msg"] = "Raw Symbol '" + name + "' was successfully deleted.";
                }
                else
                {
                    TempData["msg"] = "Could not delete symbol '" + name + "'.";
                }
            }
            else
            {
                TempData["msg"] = "Raw Symbol with id: '" + id + "' was not found.";
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Deletes all RawSymbolImports from the database.
        /// Redirects to Index-method in RawListController, together
        /// with a message of error or success.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteAll()
        {
            if (Session["logged_in"] == null)
                return RedirectToAction("Index", "Index");

            RawSymbolImportBLL rawImport = new RawSymbolImportBLL();
            TempData["msg"] = (rawImport.DeleteAll()) ? "All raw symbols deleted" : "Error trying to delete files.";
            return RedirectToAction("Index");
        }
    }
}

BlissBase/BlissBase/Views/CompositeSymbol/Edit.cshtml
@using BlissBase.Model;

@{
    ViewBag.Title = Html.Localize("edit").ToString();
    CompositeSymbol comp = ViewData["comp"] as CompositeSymbol;
    IEnumerable<Symbol> symbols = ViewData["symbList"] as IEnumerable<Symbol>;
    IEnumerable<Symbol> otherSymbols = ViewData["otherSymbols"] as IEnumerable<Symbol>;
    List<SymbolType> types = ViewData["types"] as List<SymbolType>;
}
@if (Session["logged_in"] == null)
{
    <h2>You have to logg inn to view this page</h2>
} else
{
<div class="container body-content">
    <h2 class="page-header">@Html.Localize("edit")</h2>

    <table class="table">
        <tbody>
            <tr>
                <th>@Html.Localize("symId")</th>
                <td>@comp.compId</td>
            </tr>
            <tr>
                <th>@Html.Localize("symName")</th>
                <td>@comp.compName</td>
            </tr>
            <tr>
                <th>@Html.Localize("baseId")</th>
                <td>
                    @{var ids = "";}
                    @foreach(Symbol s in symbols)
                    {
                        ids += s.symId + " - ";
                    }
                    @ids
                </td>
            </tr>
            <tr>
                <th>@Html.Localize("symImg")</th>
                @{
                    var base64 = Convert.ToBase64String(comp.compJpeg);
                    var image = String.Format("data:image/png;base64,{0}", base64);
                }
                <td><img src="@image" /></td>
            </tr>
        </tbody>
    </table>
    
    @using (Html.BeginForm())
    {
       <div>
           <a class="btn btn-primary" href="@Url.Action("Index", "CompositeSymbol")"><span class="glyphicon glyphicon-arrow-left"></span> @Html.Localize("back")</a>
           <button type="submit" name="submit" class="btn btn-danger">
               <span class="glyphicon glyphicon-ok"></span> @Html.Localize("save")
           </button>
       </div> 
        
    <div>
        <h2 class="page-header">@Html.Localize("selectSym")</h2>
        <ul class="tabs">
            <li class="tab-link current" data-tab="tab-1">@Html.Localize("symbols")</li>
            <li class="tab-link" data-tab="tab-2">@Html.Localize("indicators")</li>
            <li class="tab-link" data-tab="tab-3">@Html.Localize("letters")</li>
            <li class="tab-link" data-tab="tab-4">@Html.Localize("numbers")</li>
        </ul>

        <div id="tab-1" class="tab-content current">
            <table class="table">
                <tbody>
                    @if (symbols != null)
                    {
                        foreach (Symbol symbol in otherSymbols)
                        {
                            if (types.Find(t => t.symId == symbol.symId) == null)
                            {
                                <tr>
                                    <td>@symbol.symId</td>
                                    <td>@symbol.symName</td>
                                    @{
                                        var symbolBase64 = Convert.ToBase64String(symbol.symJpeg);
                                        var symbolImage = String.Format("data:image/png;base64,{0}", symbolBase64);
                                    }
                                    <td><img src="@symbolImage" /></td>
                                    <td>
                                        @{var checkboxCreated = false;}
                                        @foreach (Symbol isPartOfCurrentSymbol in symbols)
                                        {
                                            if (symbol.symId == isPartOfCurrentSymbol.symId)
                                            {
                                                <input type="checkbox" name="isPartOf" value="@symbol.symId" checked />
                                                checkboxCreated = true;
                                                break;
                                            }
                                        }
                                        @if (!checkboxCreated)
                                        {
                                            <input type="checkbox" name="isPartOf" value="@symbol.symId" />
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </div>

        <div id="tab-2" class="tab-content">
            <table class="table">
                <tbody>
                    @if (symbols != null)
                    {
                        foreach (Symbol symbol in otherSymbols)
                        {
                            var temp = types.Find(t => t.symId == symbol.symId);
                            if (temp != null && temp.typeIndicator.ToString() == "INDICATOR")
                            {
                                <tr>
                                    <td>@symbol.symId</td>
                                    <td>@symbol.symName</td>
                                    @{
                                        var symbolBase64 = Convert.ToBase64String(symbol.symJpeg);
                                        var symbolImage = String.Format("data:image/png;base64,{0}", symbolBase64);
                                    }
                                    <td><img src="@symbolImage" /></td>
                                    <td>
                                        @{var checkboxCreated = false;}
                                        @foreach (Symbol isPartOfCurrentSymbol in symbols)
                                        {
                                            if (symbol.symId == isPartOfCurrentSymbol.symId)
                                            {
                                                <input type="checkbox" name="isPartOf" value="@symbol.symId" checked />
                                                checkboxCreated = true;
                                                break;
                                            }
                                        }
                                        @if (!checkboxCreated)
                                        {
                                            <input type="checkbox" name="isPartOf" value="@symbol.symId" />
                                        }
                                    </td>
                                </tr>
                            }

                        }
                    }
                </tbody>
            </table>
        </div>

        <div id="tab-3" class="tab-content">
            <table class="table">
                <tbody>
                    @if (symbols != null)
                    {
                        foreach (Symbol symbol in otherSymbols)
                        {
                            var temp = types.Find(t => t.symId == symbol.symId);
                            if (temp != null && temp.typeIndicator.ToString() == "LATIN")
                            {
                                <tr>
                                    <td>@symbol.symId</td>
                                    <td>@symbol.symName</td>
                                    @{
                                        var symbolBase64 = Convert.ToBase64String(symbol.symJpeg);
                                        var symbolImage = String.Format("data:image/png;base64,{0}", symbolBase64);
                                    }
                                    <td><img src="@symbolImage" /></td>
                                    <td>
                                        @{var checkboxCreated = false;}
                                        @foreach (Symbol isPartOfCurrentSymbol in symbols)
                                        {
                                            if (symbol.symId == isPartOfCurrentSymbol.symId)
                                            {
                                                <input type="checkbox" name="isPartOf" value="@symbol.symId" checked />
                                                checkboxCreated = true;
                                                break;
                                            }
                                        }
                                        @if (!checkboxCreated)
                                        {
                                            <input type="checkbox" name="isPartOf" value="@symbol.symId" />
                                        }
                                    </td>
                                </tr>
                            }

                        }
                    }
                </tbody>
            </table>

        </div>

        <div id="tab-4" class="tab-content">
            <table class="table">
                <tbody>
                    @if (symbols != null)
                    {
                        foreach (Symbol symbol in otherSymbols)
                        {
                            var temp = types.Find(t => t.symId == symbol.symId);
                            if (temp != null && temp.typeIndicator.ToString() == "NUMERICAL")
                            {
                                <tr>
                                    <td>@symbol.symId</td>
                                    <td>@symbol.symName</td>
                                    @{
                                        var symbolBase64 = Convert.ToBase64String(symbol.symJpeg);
                                        var symbolImage = String.Format("data:image/png;base64,{0}", symbolBase64);
                                    }
                                    <td><img src="@symbolImage" /></td>
                                    <td>
                                        @{var checkboxCreated = false;}
                                        @foreach (Symbol isPartOfCurrentSymbol in symbols)
                                        {
                                            if (symbol.symId == isPartOfCurrentSymbol.symId)
                                            {
                                                <input type="checkbox" name="isPartOf" value="@symbol.symId" checked />
                                                checkboxCreated = true;
                                                break;
                                            }
                                        }
                                        @if (!checkboxCreated)
                                        {
                                            <input type="checkbox" name="isPartOf" value="@symbol.symId" />
                                        }
                                    </td>
                                </tr>
                            }

                        }
                    }
                </tbody>
            </table>
        </div>
        <input hidden name="compId" value="@comp.compId" />
        <a class="btn btn-primary" href="@Url.Action("Index", "CompositeSymbol")"><span class="glyphicon glyphicon-arrow-left"></span> @Html.Localize("back")</a>
        <button type="submit" name="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-ok"></span> @Html.Localize("save")
        </button>
    </div>
    }
    
</div>
<script type="text/javascript">
        $(document).ready(function () {

            $('ul.tabs li').click(function () {
                var tab_id = $(this).attr('data-tab');

                $('ul.tabs li').removeClass('current');
                $('.tab-content').removeClass('current');

                $(this).addClass('current');
                $("#" + tab_id).addClass('current');

            })

        })
</script>
}

BlissBase/BlissBase/Views/CompositeSymbol/Index.cshtml
@using BlissBase.Model;
@{
    ViewBag.Title = Html.Localize("compSymbol").ToString();
    IEnumerable<CompositeSymbol> comp = ViewData["comp"] as IEnumerable<CompositeSymbol>;
}
<div class="container body-content">
    <div class="container-fluid">
        <h2 class="page-header">@Html.Localize("compSymbol")</h2>
        <div class="has-success">
            <p class="control-label">@ViewBag.Message</p>
        </div>
        @if (Session["logged_in"] != null)
        {
        <div>
            <p>
                <a class="btn btn-primary" href="@Url.Action("SymbolAdministration", "Index")"><span class="glyphicon glyphicon-arrow-left"></span> @Html.Localize("backToAdmin")</a>
                <a class="btn btn-info" href="@Url.Action("Index", "RawList")"><span class="glyphicon glyphicon-list"></span> @Html.Localize("backToRaw")</a>
            </p>
        </div>
        }
        <table class="table table-striped">
            <tbody>
                <!--<tr>
                    <td>@Html.ActionLink("Back to Symbol Administration", "SymbolAdministration", "Index")</td>
                    <td>@Html.ActionLink("Back to Raw", "Index", "RawList")</td>
                </tr>-->
                <tr>
                    <th>ID</th>
                    <th>@Html.Localize("compName")</th>
                    <th>@Html.Localize("compImg")</th>
                    <th></th>
                </tr>
                @if (comp != null)
                {
                    foreach (CompositeSymbol symbol in comp)
                    {
                        <tr>
                            <td>@symbol.compId</td>
                            <td>@symbol.compName</td>
                            @{
                        var base64 = Convert.ToBase64String(symbol.compJpeg);
                        var image = String.Format("data:image/png;base64,{0}", base64);
                            }
                            <td><img src="@image" /></td>
                            @if (Session["logged_in"] != null)
                            {
                            <td>
                                @Html.ActionLink(Html.Localize("edit").ToString(), "Edit", new { id = @symbol.compId }) |
                                @Html.ActionLink(Html.Localize("delete").ToString(), "Delete", new { id = @symbol.compId })
                            </td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>